### PR TITLE
[vx.dev] implements #138

### PR DESCRIPTION
**Pull request by Yuyz0112**
[vx.dev] This PR implements #138, created by vx.dev.

### CODE REVIEW

**Comment by Yuyz0112** [comment]
[vx.dev]: This Vue component represents a high-fidelity prototype of a product page for a web3 official website. The page includes sections for a hero image with a call to action, a company introduction, services offered, showcased projects, client logos, an about us section, and a contact form. The footer includes copyright and a signature by the creator. The images are placeholders from Unsplash and should be replaced with actual project and client images. The design uses a dark theme with blue accents for buttons and links.

**Comment by adntian** [comment]
添加一些动画效果，滚动时背景也添加下错位显示效果

**Comment by Yuyz0112** [comment]
[vx.dev]: To meet your new requirements, I will enhance the existing code with some animation effects and a parallax scrolling effect for the background images. Here's the updated Vue component:

In this updated code, I've added CSS animations for a fade-in effect on the text and button elements within the hero section. Additionally, I've implemented a simple parallax effect on the background image that moves at a different speed than the scroll, creating a sense of depth. The `.parallax` class is applied to the background images, and the `@keyframes parallaxScroll` animation is used to create the parallax effect.

Please note that for a fully functional parallax effect that responds to the user's scroll actions, JavaScript would be required to dynamically adjust the background position based on the scroll position. However, since the instructions specify no additional script, I've provided a simple CSS-based animation to simulate the effect.

**Comment by Yuyz0112** [comment]
[vx.dev]: Based on the provided code and the new requirements, I will enhance the parallax effect to create a more dynamic background as the user scrolls. I will also ensure that the main content of the page is present and that the parallax effect is applied correctly. Here's the updated Vue component:

In this update, I've wrapped the background image in a `.parallax-wrapper` to control the overflow and positioning. The `.parallax` class is now applied to the image itself, which is positioned absolutely within the wrapper to create the parallax effect. The `height` of the `.parallax-wrapper` is set to `96vh` to ensure it covers most of the viewport height, enhancing the parallax effect as the user scrolls.

Please note that the actual parallax scrolling effect that changes as the user scrolls the page cannot be achieved with CSS animations alone. It requires JavaScript to dynamically adjust the `transform` property of the `.parallax` element based on the scroll position. However, since the instructions specify no additional script, I've provided a CSS-only solution that simulates the effect on page load. For a true parallax effect, you would need to implement a scroll event listener in JavaScript.

**Pull request closed without merging**
